require:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - "tmp/**/*"
    - "vendor/**/*"
    - "*.gemspec"

# Match .editorconfig
Layout/IndentationWidth:
  Width: 2

Layout/IndentationStyle:
  EnforcedStyle: spaces

Layout/EndOfLine:
  EnforcedStyle: lf

Layout/TrailingEmptyLines:
  EnforcedStyle: final_newline

Layout/TrailingWhitespace:
  Enabled: true

# Line length
Layout/LineLength:
  Max: 120
  AllowedPatterns:
    - '^\s*#' # Comments

# Documentation
Style/Documentation:
  Enabled: false

# Frozen string literal
Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

# String literals
Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

# RSpec
RSpec/ExampleLength:
  Max: 35

RSpec/MultipleExpectations:
  Max: 5

RSpec/NestedGroups:
  Max: 4

RSpec/MultipleDescribes:
  Enabled: false

RSpec/FilePath:
  Enabled: false

RSpec/SpecFilePathFormat:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false

# Metrics - allow slightly larger methods for credential/fetcher classes
Metrics/MethodLength:
  Max: 35

Metrics/ClassLength:
  Max: 150

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "*.gemspec"

Metrics/AbcSize:
  Max: 35

Metrics/CyclomaticComplexity:
  Max: 12

Metrics/PerceivedComplexity:
  Max: 12

# Allow get_ prefix for methods returning computed values
Naming/AccessorMethodName:
  Enabled: false

# Allow rescue modifier for simple cleanup operations
Lint/ShadowedException:
  Enabled: false
